ecommerce/ecomproject/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<int:product_id>',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>',views.cart_remove,name='cart_remove'),
    path('delete/<int:product_id>',views.delete,name='delete')]

ecommerce/ecomproject/ecomapp/urls.py
from django.urls import path
from . import views
app_name='ecomapp'

urlpatterns = [
    path('',views.AllProdCat,name='AllProdCat'),
    path('<slug:c_slug>/',views.AllProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatDetail'),
]

ecommerce/ecomproject/ecomproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecomapp/',include('ecomapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
     urlpatterns +=static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
     urlpatterns +=static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerce/ecomproject/search_app/urls.py
from django.urls import path
from . import views
app_name='search_app'

urlpatterns = [
    path('',views.SearchResult,name='SearchResult'),]

ecommerce/ecomproject/cart/models.py
from django.db import models
from ecomapp.models import Product


class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)


    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    qty=models.IntegerField()
    active=models.BooleanField(default=True)


    class Meta:
        db_table='CartItem'

    def SubTotal(self):
        return self.product.price * self.qty

    def __str__(self):
        return self.product

ecommerce/ecomproject/ecomapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('ecomapp:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    modified=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def get_url(self):
        return reverse('ecomapp:prodCatDetail', args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

ecommerce/ecomproject/search_app/models.py
from django.db import models

# Create your models here.

ecommerce/ecomproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecomapp.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return Cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
                cart_id=_cart_id(request)
            )
        cart.save(),
    try:
        cart_item = CartItem.objects.get(product=product,cart=cart)
        if cart_item.qty < cart_item.product.stock:
            cart_item.qty +=1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            qty=1,
            cart=cart
            )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.qty)
            counter += cart_item.qty

    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(total=total,counter=counter,cart_items=cart_items))

def cart_remove(request, product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.qty > 1:
        cart_item.qty -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def delete(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerce/ecomproject/ecomapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage


# Create your views here

def index(request):
    return HttpResponse("index")

def AllProdCat(request,c_slug=None):
    c_page=None
    product_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        product_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        product_list=Product.objects.all().filter(available=True)
    paginator=Paginator(product_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,"category.html",{'category':c_page,'products':products})

def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,"product.html",{'product':product})

ecommerce/ecomproject/search_app/views.py
from django.shortcuts import render
from ecomapp.models import Product
from django.db.models import Q



def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

ecommerce/ecomproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.min.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% include 'header.html' %}
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>
{% include 'footer.html' %}
 <script src="{% static 'js/popper.min.js' %}"></script>
 <script src="{% static 'js/bootstrap.min.js' %}" ></script>

</body>
</html>

ecommerce/ecomproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Cart Page---->Review your items and place your order
{% endblock %}

{% block title %}
         Cart-Pink
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
    <br>
    <h1 class="text-center my_title">
        Your shopping cart is empty!
    </h1>
    <br>
    <p class="text-center">
        Please click <a href="{% url 'ecomapp:AllProdCat' %}">here</a>to continue shopping
    </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
    <br>
    <h1 class="text-center my_title">
            Your Shopping Cart
    </h1>
    <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_table">
            <thead class="my_thead">
                <tr>
                    <th colspan="5">
                        Your items
                    </th>
                </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" height="150px;" width="150px;" class="float-left rounded image"></a>
                </td>

                <td class="text-left">
                    {{ cart_item.product.name }}
                    <br>
                    SKU: {{ cart_item.product.id }}
                    <br>
                    Price: $ {{ cart_item.product.price }}
                    <br>
                    Qty: {{cart_item.qty}} x $ {{cart_item.product}}
                </td>
                <td>
                    $ {{cart_item.SubTotal}}
                </td>
                {% if cart_item.qty < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:delete' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:delete' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_table">
            <thead class="my_thead">
                <tr>
                    <th>
                        Check Out
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                    <br>
                        Please review the items in your cart and place your order
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                         Total product price is: <strong>{{ total }}</strong>
                    </td>
                </tr>
                </tbody>
            </table>
            <br><br>
            <div class="row mx-auto">
                <div class="bt1">
                <a href="{% url 'ecomapp:AllProdCat' %}" class="btn btn-secondary btn-sm">Continue shopping</a>
                <a href="{% url 'ecomapp:AllProdCat' %}" class="btn btn-secondary btn-sm">Place your order</a>
                </div>
            </div>
    </div>
    {% endif %}
</div>
{% endblock %}

ecommerce/ecomproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if category %}
      {{ category.description | truncatewords:155 }}
  {% else %}
      Welcome to Pink!
  {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
      {{ category.name }} - Pink
    {% else %}
        Pink Pink Pink
    {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
        <div>
            <div>
                <a href="{% url 'ecomapp:AllProdCat' %}">Our Collections</a>
            </div>
        </div>
    {% endif %}
    <div>
        {% if category %}
            <img src="{{category.image.url}}" alt="{{category.name}}" width="250px;" height="250px;">
    </div>
    <br>
    <div>
        <h1>{{category.name}}</h1>
        <p>{{category.description}}</p>
    </div>
        {% else %}
          <div>
                    <img src="{% static 'img/banner.png' %}" alt="All Collections" width="1115px;" height="300px;">
            </div>
            <br>
            <div>
                <h1>Pink Collections</h1>
                <p>
                    It is a long established fact that a reader will be distracted by the readable content of a page
                    when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal
                    distribution of letters, as opposed to using 'Content here, content here', making it look like
                    readable English.
                    Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text,
                    and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions
                    have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
                </p>
            </div>
        {% endif %}
        <div class="container">
            <div class="row mx_auto">
                {% for product in products.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
                    <div class="card text-center" style="width: 20rem;">
                        <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" width="250px;" height="350px;"></a>
                        <div class="card-body">
                            <h4>{{product.name}}</h4>
                            <p>{{product.price}}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="mx-auto">
                {% if products.paginator.num_pages > 1 %}
               <br>
                <div class="my_paginator">
                    <div class="text-center">
                        {% for pg in products.paginator.page_range %}
                            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                        {% endfor %}
                    </div>
                {% endif %}
                </div>
                <br>
            </div>
        </div>
{% endblock %}

ecommerce/ecomproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">
        &copy; Pink Pvt Ltd.All rights reserved
    </p>
</div>

ecommerce/ecomproject/templates/header.html
{% load static %}
<header>
  <center>
     <a href="{% url 'ecomapp:AllProdCat' %}"><img src="{% static 'img/log.png' %}" alt="logoimg" height="100px;" width="100px;"></a>
  </center>
</header>

ecommerce/ecomproject/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Pink</a>
        </li>
        <li class="nav-item dropdown {% if 'ecomapp' in request.path %} active {% endif %} ">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'ecomapp:AllProdCat' %}">All Products</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{ cat.get_url }}">{{cat.name}}</a></li>
              {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" role="search" action="{% url 'search_app:SearchResult' %}" method="get">
          {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce/ecomproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{ product.description | truncatewords:155 }}
{% endblock %}

{% block title %}
{% if category %}
    {{product.name}}-Pink
{% endif %}
{% endblock %}

{% block content %}

<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p> <a href="{% url 'ecomapp:AllProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}} </p>
    </div>
</div>
<br>
<div class="container">
    <br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width:18rem;">
                <img src="{{product.image.url}}" alt="{{product.name}}" width="500px;" height="500px;">
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
            <h4 class="my_prd_title">{{product.name}}</h4>
            <p>{{product.price}}</p>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prd_text">{{product.description}}</p>
                {% if product.stock <= 0 %}
                    <p class="text-justify my_prd_text"><b>Out of Stock</b></p>
                {% else %}
                    <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

ecommerce/ecomproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
      Welcome to Pink!
{% endblock %}

{% block title %}
    Search
{% endblock %}

{% block content %}

<div>

    <p class="text-center my_search_text">Your search results:<b>"{{query}}"</b></p>

</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
                <div class="card text-center" style="width: 20rem;">
                    <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" width="250px;" height="350px;"></a>
                    <div class="card-body">
                        <h4>{{product.name}}</h4>
                        <p>{{product.price}}</p>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="row mx-auto">
                <p class="text-center my_search_text">0 results found</p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}