movies/moviesproject1/moviesapp1/urls.py
from . import views
from django.urls import path
app_name='moviesapp1'

urlpatterns = [
    path('', views.index,name="index"),
    path('movie/<int:movie_id>/',views.detail,name="detail"),
    path('add/',views.add_movies,name="add_movies"),
    path('update/<int:movie_id>/',views.update,name="update"),
    path('delete/<int:movie_id>/',views.delete,name="delete")
]

movies/moviesproject1/moviesproject1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moviesapp1.urls')),
]

if settings.DEBUG:
     urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
     urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movies/moviesproject1/moviesapp1/models.py
from django.db import models

class movies_dtl(models.Model):
    name=models.CharField(max_length=150)
    year=models.IntegerField()
    desc=models.TextField()
    pic=models.ImageField(upload_to='imgs')

movies/moviesproject1/moviesapp1/forms.py
from django import forms
from . models import movies_dtl

class MovieForm(forms.ModelForm):
    class Meta:
        model=movies_dtl
        fields=['name','year','desc','pic']

movies/moviesproject1/moviesapp1/views.py
from django.http import HttpResponse
from . models import movies_dtl
from django.shortcuts import render, redirect
from . forms import MovieForm


def index(request):
    movies=movies_dtl.objects.all()
    context={
        'movies_list': movies
    }
    return render(request,"index.html",context)

def detail(request,movie_id):
    movie=movies_dtl.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})

def add_movies(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        year=request.POST.get('year',)
        desc=request.POST.get('desc',)
        pic=request.FILES['pic']
        movie=movies_dtl(name=name,year=year,desc=desc,pic=pic)
        movie.save()
    return render(request,"add.html")

def update(request,movie_id):
    movie=movies_dtl.objects.get(id=movie_id)
    form=MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html", {'form':form,'movie':movie})
def delete(request,movie_id):
    if request.method=='POST':
        movie=movies_dtl.objects.get(id=movie_id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movies/moviesproject1/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {%csrf_token%}

    <input type="text" name="name" placeholder="Enter Movie name">
    <input type="text" name="year" placeholder="Enter Relaesed year">
    <input type="text" name="desc" placeholder="Enter Movie description">
    <input type="file" name="pic">
    <input type="submit" value="add">

</form>
{% endblock %}

movies/moviesproject1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      Movies2Watch
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movies/moviesproject1/templates/delete.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  Do you want to delete this movie?
  <input type="submit">

</form>

movies/moviesproject1/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.pic.url}}" width="300px" >
          </div>
         <div class="col-md-6">
             <h4><b>{{movie.name}}({{movie.year}})</b></h4>
           <h6>{{movie.desc}}</h6>
            <a class="btn btn-warning" href="{% url 'moviesapp1:update' movie.id %}" >Update</a>
            <a class="btn btn-danger" href="{% url 'moviesapp1:delete' movie.id %}" >Delete</a>
         </div>
    </div>
</div>
{% endblock %}

movies/moviesproject1/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

movies/moviesproject1/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movies_list %}
        <div class="col-md-3">
        <div class="card" style="width: 18rem;height: 55rem; padding:10px;">
        <img src="{{i.pic.url}}" alt="Card image cap" height="300px" >
        <div class="card-body">
        <h5 class="card-title">{{i.name}}</h5>
        <p class="card-text">{{i.desc}}</p>
        <a href="{% url 'moviesapp1:detail' i.id %}" class="btn btn-primary">Read More</a>
         </div>
  </div>
</div>
        {% endfor %}
    </div>
</div>

{% endblock %}